# Generated by Django 4.0.6 on 2022-07-12 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('commits', models.IntegerField()),
                ('done', models.IntegerField()),
            ],
            options={
                'ordering': ['commits'],
            },
        ),
    ]
