# Generated by Django 4.0.6 on 2022-07-13 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todos', '0002_alter_todoitem_options_todoitem_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='author',
            field=models.ForeignKey(default='author_name', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
