# Generated by Django 4.0.6 on 2022-07-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_alter_todoitem_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='commits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='done',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='title',
            field=models.CharField(max_length=140, unique=True),
        ),
    ]
